version: "3.9"
services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - datasets:/data
    command:  minio server /data --console-address ":9001"
  pyspark:
    container_name: pyspark
    build: .
    ports:
      - "8888:8888"
      - "4040:4040"
      - "4041:4041"
    volumes:
      - notebook:/home/jovyan/work/notebook
      - datasets:/home/jovyan/work/datasets
    command: start-notebook.sh --NotebookApp.token='' && chown joyvan:joyvan /home/jovyan/work/notebook
volumes:
  notebook:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ../spark/notebook
      o: bind
  datasets:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ../datasets
      o: bind